name: "Sync README to Notion"

on:
  push:

jobs:
  notion:
    uses: catie-aq/generic_workflows/.github/workflows/notion.yml@main
    with:
      notion-page-id: "9f87732a9c5f4f88af950eb54c542453"
    secrets:
      notion-token: ${{ secrets.NOTION_TOKEN }}
