name: Publish new tag and pre-release when version is bumped

on:
  workflow_call:
    inputs:
      image:
        type: string
        description: "The name of the image to build"
        required: false
        default: "ubuntu:22.04"

jobs:
  bump-tag:
    uses: catie-aq/generic_workflows/.github/workflows/autotag.yml@main
    with:
      image: ${{ inputs.image }}
      version_cmd: grep "<version>" package.xml | sed -n 's|<version>\(.*\)</version>|\1|p' | tr -d ' '
