name: Build & Test ROS Packages

on:
  workflow_call:

jobs:
  build_and_test_ros_package:
    runs-on: self-hosted # Use self-hosted runner
    strategy: # Define a matrix of ROS distributions and Docker images
      matrix:
        include:
          - docker_image: osrf/ros:noetic-desktop-full
        env:
          - {ROS_DISTRO : noetic, ROS_REPO: "main"}
    container: # Use the Docker image defined in the matrix
      image: ${{ matrix.docker_image }}
    steps:
      - name: Build and test ROS
        uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
