name: CI

on:
  workflow_call:
    

jobs:
  industrial_ci:
    runs-on: self-hosted
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: melodic, ROS_REPO: main, DOCKER_IMAGE: osrf/ros:melodic-desktop-full }
          - { ROS_DISTRO: noetic, ROS_REPO: main, DOCKER_IMAGE: osrf/ros:noetic-desktop-full }
    container:
      image: ${{ matrix.DOCKER_IMAGE }}
    steps:
      - name: Setup ROS environment
        uses: actions/checkout@v3
      - name: Build and test ROS
        uses: 'ros-industrial/industrial_ci@0.10.0'
        env: ${{matrix.env}}