name: Build & Test ROS Packages

on:
  workflow_call:
    inputs:
      package-name:
        description: 'The name of the ROS package to build and test.'
        required: true
        type: string
    secrets:
      PAT:
        required: false
        description: 'A GitHub Personal Access Token (PAT) used to import the private repository into the container.'
        

jobs:
  pre-commit:
    uses: catie-aq/generic_workflows/.github/workflows/pre-commit.yaml@main
  build_and_test_ros_package:
    runs-on: self-hosted # Use self-hosted runner
    strategy: # Define a matrix of ROS distributions and Docker images
      matrix:
        include:
          - docker_image: osrf/ros:noetic-desktop-full
            ros_distribution: noetic
          - docker_image: osrf/ros:melodic-desktop-full
            ros_distribution: melodic
    container: # Use the Docker image defined in the matrix
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Build and test ROS
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: ${{ inputs.package-name }}
          target-ros1-distro: ${{ matrix.ros_distribution }}
          import-token: ${{ secrets.PAT }}