name: CI

on: workflow_call

jobs:
  industrial_ci:
    runs-on: self-hosted
    strategy:
      matrix:
        include:
          - docker_image: ubuntu:bionic
            ros_distribution: melodic
          - docker_image: ubuntu:focal
            ros_distribution: noetic
    steps:
      - name: Setup ROS environment
        uses: actions/checkout@v3
      - name: Build and test ROS
        uses: 'ros-industrial/industrial_ci@0.10.0'
        env:
          ROS_DISTRO: ${{ matrix.ros_distribution }}
          ROS_REPO: main
