name: Build & Test ROS 2 Packages

on:
  push:
  pull_request:
  workflow_call:

jobs:
  build_and_test_ros2_package:
    runs-on: self-hosted # Use self-hosted runner
    strategy: # Define a matrix of ROS distributions and Docker images
      matrix:
        include:
          - docker_image: osrf/ros:humble-desktop-full
            ros_distribution: humble
          - docker_image: osrf/ros:rolling-desktop-full-jammy
            ros_distribution: rolling

    container: # Use the Docker image defined in the matrix
      image: ${{ matrix.docker_image }}
    steps:
      - name: ROS2 Action
        uses: catie-aq/ros_action@humble
        with:
          ros_distribution: ${{ matrix.ros_distribution }}

