name: Build & Test ROS 2 Packages

on:
  workflow_call:
    secrets:
      PAT:
        required: true
        description: "A GitHub Personal Access Token (PAT) used to import the private repository into the container. Pass GITHUB_TOKEN if the repository is public."

jobs:
  build_and_test_ros2_package:
    runs-on: sonu-github-arc
    strategy: # Define a matrix of ROS distributions and Docker images
      fail-fast: false
      matrix:
        include:
          - docker_image: osrf/ros:humble-desktop
            ros_distribution: humble
          - docker_image: osrf/ros:jazzy-desktop
            ros_distribution: jazzy
          - docker_image: osrf/ros:rolling-desktop
            ros_distribution: rolling

    container: # Use the Docker image defined in the matrix
      image: ${{ matrix.docker_image }}
    steps:
      - name: Build and test ROS 2
        uses: ros-tooling/action-ros-ci@0.3.13
        with:
          package-name: ${{ github.event.repository.name }}
          target-ros2-distro: ${{ matrix.ros_distribution }}
          import-token: ${{ secrets.PAT }}
          skip-tests: true
          skip-rosdep-install: true
          rosdep-check: false
